services:
  prometheus:
    image: prom/prometheus-linux-amd64
    container_name: prome
    hostname: prome
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/data
    ports:
      - 9090:9090
    networks:
      - mybridge 
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    networks:
      - mybridge
networks:
  mybridge:
    driver: bridge
