test:
  topic: coupon
server:
  port: 8081
management:
  metrics:
    tags:
      application:
        ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus
---
spring:
  application:
    name: coupon-api
  config:
    activate:
      on-profile: local
  kafka:
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: coupon-issue-0
    properties:
        spring.json.trusted.packages: '*'
    bootstrap-servers: localhost:9094
---
spring:
  config:
    activate:
      on-profile: test
  kafka:
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: coupon-issue-0
    properties:
      spring.json.trusted.packages: '*'
    bootstrap-servers: localhost:9094
---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: coupon-issue-0
    properties:
      spring.json.trusted.packages: '*'
    bootstrap-servers: PROD_URL:9094
